In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2

In [2]:
df = pd.read_excel("../Data/Raw_data_corrected.xls")
df.head()

Grouping Age (years)           Education    Working status Marital status  \
0       BC       >= 50  Senior high school         Housewife       Marriage   
1   Non-BC       >= 50   Vocational degree  Master's student  Single/ widow   
2       BC       >= 50  Senior high school         Housewife       Marriage   
3   Non-BC       >= 50  Senior high school  Master's student       Marriage   
4       BC       >= 50  Senior high school   Private servant       Marriage   

  Menarche (years)   Menopause First pregnancy          Parity Breastfeeding  \
0        12  to 13  < 50 years     20-29 years  >= Multiparous   >=12 months   
1              >13  < 50 years       >30 years  >= Multiparous    <12 months   
2          7 to 11  < 50 years     20-29 years  >= Multiparous   >=12 months   
3        12  to 13  < 50 years     20-29 years     Primiparous   >=12 months   
4              >13  < 50 years     20-29 years  >= Multiparous   >=12 months   

  Highfat      BMI   Ethnicity  
0  Normal  Obesity  Minangnese  
1    High   Normal  Minangnese  
2  Normal   Normal    Javanese  
3    High   Normal    Javanese  
4    High   Normal  Minangnese

In [3]:
df.isnull().sum()

Grouping            0
Age (years)         0
Education           0
Working status      0
Marital status      0
Menarche (years)    0
Menopause           0
First pregnancy     0
Parity              0
Breastfeeding       0
Highfat             0
BMI                 0
Ethnicity           0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Grouping          400 non-null    object
 1   Age (years)       400 non-null    object
 2   Education         400 non-null    object
 3   Working status    400 non-null    object
 4   Marital status    400 non-null    object
 5   Menarche (years)  400 non-null    object
 6   Menopause         400 non-null    object
 7   First pregnancy   400 non-null    object
 8   Parity            400 non-null    object
 9   Breastfeeding     400 non-null    object
 10  Highfat           400 non-null    object
 11  BMI               400 non-null    object
 12  Ethnicity         400 non-null    object
dtypes: object(13)
memory usage: 40.8+ KB


In [5]:
for col in df.columns:
    print(f"{col}: {np.unique(df[col])}")

Grouping: ['BC' 'Non-BC']
Age (years): ['< 50' '>= 50']
Education: ['Elementary school' 'Junior high school' 'Master degree' 'No school'
 'Senior high school' 'Undergraduate degree' 'Vocational degree']
Working status: ['Civil servant' 'Enterpreneur' 'Farmer' 'Housewife' "Master's student"
 'Private servant' 'Retired']
Marital status: ['Marriage' 'Single/ widow']
Menarche (years): ['12  to 13' '7 to 11' '>13']
Menopause: ['< 50 years' '>= 50 years']
First pregnancy: ['20-29 years' '< 20 years' '>30 years' 'None']
Parity: ['>= Multiparous' 'Nulliparous' 'Primiparous']
Breastfeeding: ['<12 months' '>=12 months']
Highfat: ['High' 'Normal']
BMI: ['Normal' 'Obesity' 'Overweight']
Ethnicity: ['Javanese' 'Minangnese']


In [6]:
for col in df.columns:
    df[col].replace(np.unique(df[col]), [i for i in range(len(np.unique(df[col])))], inplace=True)

df.head()

Grouping  Age (years)  Education  Working status  Marital status  \
0         0            1          4               3               0   
1         1            1          6               4               1   
2         0            1          4               3               0   
3         1            1          4               4               0   
4         0            1          4               5               0   

   Menarche (years)  Menopause  First pregnancy  Parity  Breastfeeding  \
0                 0          0                0       0              1   
1                 2          0                2       0              0   
2                 1          0                0       0              1   
3                 0          0                0       2              1   
4                 2          0                0       0              1   

   Highfat  BMI  Ethnicity  
0        1    1          1  
1        0    0          1  
2        1    0          0  
3        0    0          0  
4        0    0          1

In [7]:
for col in df.columns:
    print(f"{col}: {np.unique(df[col])}")

Grouping: [0 1]
Age (years): [0 1]
Education: [0 1 2 3 4 5 6]
Working status: [0 1 2 3 4 5 6]
Marital status: [0 1]
Menarche (years): [0 1 2]
Menopause: [0 1]
First pregnancy: [0 1 2 3]
Parity: [0 1 2]
Breastfeeding: [0 1]
Highfat: [0 1]
BMI: [0 1 2]
Ethnicity: [0 1]


In [8]:
X, y = df.iloc[:, 1:], df.iloc[:, 0]

X.head()

Age (years)  Education  Working status  Marital status  Menarche (years)  \
0            1          4               3               0                 0   
1            1          6               4               1                 2   
2            1          4               3               0                 1   
3            1          4               4               0                 0   
4            1          4               5               0                 2   

   Menopause  First pregnancy  Parity  Breastfeeding  Highfat  BMI  Ethnicity  
0          0                0       0              1        1    1          1  
1          0                2       0              0        0    0          1  
2          0                0       0              1        1    0          0  
3          0                0       2              1        0    0          0  
4          0                0       0              1        0    0          1

In [9]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: Grouping, dtype: int64

In [10]:
len(X.columns)

12

In [11]:
k = 5

In [12]:
selector = SelectKBest(chi2, k=k)
selector.fit(X, y)

SelectKBest(k=5, score_func=<function chi2 at 0x0000020E81ED5C60>)

In [13]:
scores = selector.scores_
scores

array([ 0.54751131,  1.19350474, 40.23063534,  1.68421053,  0.83937824,
        8.82      ,  1.95180723,  7.4496124 ,  4.73521127, 90.13333333,
       12.24696356,  0.        ])

In [23]:
top_k_features = scores.argsort()[::-1]
top_k_features

array([ 9,  2, 10,  5,  7,  8,  6,  3,  1,  4,  0, 11], dtype=int64)

In [25]:
best_features = X.columns[top_k_features]
best_features

Index(['Highfat', 'Working status', 'BMI', 'Menopause', 'Parity',
       'Breastfeeding', 'First pregnancy', 'Marital status', 'Education',
       'Menarche (years)', 'Age (years)', 'Ethnicity'],
      dtype='object')

In [16]:
f_scores = chi2(X, y)

In [17]:
f_scores

(array([ 0.54751131,  1.19350474, 40.23063534,  1.68421053,  0.83937824,
         8.82      ,  1.95180723,  7.4496124 ,  4.73521127, 90.13333333,
        12.24696356,  0.        ]),
 array([4.59336357e-01, 2.74623748e-01, 2.25681303e-10, 1.94365911e-01,
        3.59574656e-01, 2.97946666e-03, 1.62392238e-01, 6.34501111e-03,
        2.95512186e-02, 2.22638976e-21, 4.66015879e-04, 1.00000000e+00]))

In [18]:
p_values = pd.Series(f_scores[1])

In [19]:
p_values.sort_values(ascending=True)

9     2.226390e-21
2     2.256813e-10
10    4.660159e-04
5     2.979467e-03
7     6.345011e-03
8     2.955122e-02
6     1.623922e-01
3     1.943659e-01
1     2.746237e-01
4     3.595747e-01
0     4.593364e-01
11    1.000000e+00
dtype: float64

In [20]:
p_values.index = X.columns

In [21]:
p_values.sort_values(ascending=True)

Highfat             2.226390e-21
Working status      2.256813e-10
BMI                 4.660159e-04
Menopause           2.979467e-03
Parity              6.345011e-03
Breastfeeding       2.955122e-02
First pregnancy     1.623922e-01
Marital status      1.943659e-01
Education           2.746237e-01
Menarche (years)    3.595747e-01
Age (years)         4.593364e-01
Ethnicity           1.000000e+00
dtype: float64